"""add_attendance_presenter_order

Revision ID: 078854a32784
Revises: 2576f4f9f7fd
Create Date: 2026-04-19 08:20:04.096902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078854a32784'
down_revision: Union[str, None] = '2576f4f9f7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('presenter_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'presenter_order')
    # ### end Alembic commands ###
