"""add_users_table

Revision ID: 16f063455561
Revises: c824f4eea459
Create Date: 2026-02-28 22:42:30.550068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f063455561'
down_revision: Union[str, None] = 'c824f4eea459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='viewer', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('admin','manager','viewer')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )

    # Seed users
    users_table = sa.table(
        'users',
        sa.column('username', sa.String),
        sa.column('password_hash', sa.String),
        sa.column('display_name', sa.String),
        sa.column('role', sa.String),
    )
    op.bulk_insert(users_table, [
        {
            'username': 'admin',
            'password_hash': '$2b$12$N/iYtriOw89F62jJpJdnc.3Ns4QSayrpE177dAdfoRqyTZQ1Hz8Xq',
            'display_name': '관리자',
            'role': 'admin',
        },
        {
            'username': 'manager',
            'password_hash': '$2b$12$Mcp2YJxqqkEsKBXsj4OKme4mUmWyEQ7cruI1l.Ov2tlO4ymKRED6C',
            'display_name': '운영진',
            'role': 'manager',
        },
        {
            'username': 'viewer',
            'password_hash': '$2b$12$Oh8.Cde/FNxx2M96r1dzg.qaLFQusBhQ2Rv10IvC352j/RHs7ulQ6',
            'display_name': '열람자',
            'role': 'viewer',
        },
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
