"""add_note_to_attendance

Revision ID: 2576f4f9f7fd
Revises: 489add7af901
Create Date: 2026-04-02 03:40:51.466175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2576f4f9f7fd'
down_revision: Union[str, None] = '489add7af901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'note')
    # ### end Alembic commands ###
