"""drop_is_leader_from_team_members

Revision ID: 911b3aacfed8
Revises: 2f75826f6c04
Create Date: 2026-02-20 21:43:22.619486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911b3aacfed8'
down_revision: Union[str, None] = '2f75826f6c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'is_leader')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('is_leader', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
