"""add_cafe_posts_and_assignment_target_member_ids

Revision ID: c824f4eea459
Revises: 911b3aacfed8
Create Date: 2026-02-23 01:14:28.722434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c824f4eea459'
down_revision: Union[str, None] = '911b3aacfed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('board_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('author_nick', sa.String(length=100), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('week_num', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('first_seen_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_synced_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("board_type IN ('REVIEW','HOMEWORK','VIDEO')", name='ck_cafe_posts_board_type'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.add_column('assignments', sa.Column('target_member_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'target_member_ids')
    op.drop_table('cafe_posts')
    # ### end Alembic commands ###
